In [90]:
import pandas as pd
import numpy as np

In [91]:
df_customers = pd.read_csv('../data/customers.csv')
df_payments = pd.read_csv('../data/payments.csv', sep='^')
df_orders = pd.read_json('../data/orders.json')
df_products = pd.read_excel('../data/products.xlsx', engine='openpyxl')
df_events = pd.read_xml('../data/events.xml')

print("ТАБЛИЦА КЛИЕНТОВ")
display(df_customers.head(10))

print("\nТАБЛИЦА ПЛАТЕЖЕЙ")
display(df_payments.head(10))

print("\nТАБЛИЦА ЗАКАЗОВ")
display(df_orders.head(10))

print("\nТАБЛИЦА ТОВАРОВ")
display(df_products.head(10))

print("\nТАБЛИЦА СОБЫТИЙ")
display(df_events.head(10))

ТАБЛИЦА КЛИЕНТОВ

,customer_id,full_name,email,phone,city,created_at
0,1,Мишин Емельян Валерьевич,mechislav_37@hotmail.com,UNKNOWN,п. Печора,2024-05-31
1,2,Егоров Тихон Федосеевич,serafim_1986@gmail.com,UNKNOWN,п. Мостовской,2024-07-21
2,3,Зыков Вацлав Алексеевич,fharitonova@gmail.com,9749621470,ст. Луга,2024-06-15
3,4,Савельева Юлия Кузьминична,odintsovgerman@ignatev.biz,NaN,п. Воскресенск,2025-03-28
4,5,София Тимофеевна Михеева,selivan_1979@ao.ru,9206468299,г. Уренгой,2026-01-17
5,6,Варвара Степановна Шилова,aksenovkazimir@rao.biz,9298471886,п. Карпинск,2025-06-15
6,7,Гедеон Феофанович Андреев,belovemmanuil@hotmail.com,NaN,п. Руза,2023-06-08
7,8,Орехова Ангелина Дмитриевна,nonna_92@hotmail.com,+79993631208,клх Красная Поляна,2025-03-05
8,9,София Константиновна Полякова,lavrnekrasov@yahoo.com,NaN,с. Петушки,2024-12-16
9,10,Евдокия Аркадьевна Ларионова,elise1970@gmail.com,9282116655,г. Бийск,2025-09-21

ТАБЛИЦА ПЛАТЕЖЕЙ

,payment_id,order_id,payment_method,amount,currency,payment_timestamp
0,1,778,bank_transfer,error_amount,EUR,2025-04-14 23:23:52
1,2,941,bank_transfer,407.42,USD,2024-12-15 23:01:24
2,3,1173,paypal,1754.7,USD,2025-05-03 14:55:30
3,4,143,card,2372.04,RUB,2026-02-05 00:19:38
4,5,864,card,2366.62,EUR,2025-06-18 21:21:20
5,6,1139,NaN,747.97,RUB,2025-02-03 15:11:50
6,7,239,card,error_amount,EUR,2026-01-01 19:45:57
7,8,14,bank_transfer,1189.89,RUB,2025-05-05 22:59:37
8,9,685,NaN,1016.84,EUR,2025-01-18 04:06:47
9,10,1216,NaN,2574.49,EUR,2026-02-22 05:19:19

ТАБЛИЦА ЗАКАЗОВ

,order_id,customer_id,product_id,quantity,unit_price,currency,order_timestamp,status
0,1,380.0,512,3,256.02,USD,2025-99-99,processing
1,2,467.0,117,5,218.67,EUR,2026-02-18 02:28:23,completed
2,3,470.0,391,5,89.70,EUR,2025-01-14 11:22:12,cancelled
3,4,676.0,90,3,354.03,USD,2025-05-30 03:09:57,completed
4,5,92.0,639,4,60.80,RUB,2025-01-22 15:48:14,processing
5,6,103.0,217,1,337.18,EUR,2024-12-12 04:11:41,completed
6,7,466.0,476,4,475.77,EUR,2024-12-17 00:16:14,cancelled
7,8,661.0,520,1,470.41,USD,2024-12-30 16:57:31,cancelled
8,9,275.0,425,4,339.92,USD,2025-04-05 12:29:27,completed
9,10,NaN,326,5,411.82,RUB,2026-01-21 03:56:04,cancelled

ТАБЛИЦА ТОВАРОВ

   product_id product_name     category    price currency  is_active
0           1      Господь         Home    54.47      USD      False
1           2        Набор        Books   114.79      EUR       True
2           3  Вздрагивать  Electronics    49.98      RUB      False
3           4      Фонарик  Electronics   392.93      RUB      False
4           5      Фонарик     Clothing   798.13      EUR       True
5           6      Холодно       Sports   572.88      USD       True
6           7      Порядок     Clothing  1457.07      EUR       True
7           8     Академик     Clothing  1612.32      USD       True
8           9         Куча       Sports   291.56      EUR       True
9          10          Чем  Electronics  1866.64      EUR      False

ТАБЛИЦА СОБЫТИЙ

  event_id  customer_id event_type      event_timestamp  product_id
0        1        483.0       view  2025-06-23 18:40:09       281.0
1        2        550.0      login  2025-11-30 00:01:33        20.0
2        3        570.0      login  2025-02-16 21:53:55       588.0
3        4        213.0       view  2025-07-12 08:14:08       408.0
4        5        202.0   purchase  2025-04-03 12:11:22       453.0
5        6        407.0   purchase  2025-09-16 03:22:28       593.0
6        7        649.0   purchase  2025-12-19 00:43:43       416.0
7        8        211.0      click  2025-08-19 00:00:37       472.0
8        9        143.0     logout  2025-09-11 03:25:39       603.0
9       10        646.0       view  2024-10-25 05:32:16       587.0

Задание 1, избавлюсь от дубликатов и приведу все пропуски, nan, unknown к единому формату

In [92]:
df_customers_clean = df_customers.copy()
df_payments_clean = df_payments.copy()
df_orders_clean = df_orders.copy()
df_products_clean = df_products.copy()
df_events_clean = df_events.copy()

dict_of_dfs = {
    'customers': df_customers_clean,
    'payments': df_payments_clean,
    'orders': df_orders_clean,
    'products': df_products_clean,
    'events': df_events_clean
}

primary_keys = {
    'customers': 'customer_id',
    'products': 'product_id',
    'orders': 'order_id',
    'payments': 'payment_id',
    'events': 'event_id'
}

for name, df in dict_of_dfs.items():
    df = df.drop_duplicates().copy()
    pk = primary_keys.get(name)

    if pk in df.columns:

        dup_count = df[pk].duplicated().sum()

        if dup_count > 0:
            print(f'{name}: найдено дублей по {pk}: {dup_count}')

            df = df.drop_duplicates(
                subset=[pk],
                keep='first'
            )
        df = df[df[pk].notna()].copy()
    for column in df.columns:

        df[column] = df[column].replace(
            [
                'UNKNOWN',
                'unknown',
                'UNKNOWN ',
                'unknown ',
                'nan',
                'NaN',
                ''
            ],
            pd.NA
        )

        if df[column].dtype == 'object':

            df[column] = (
                df[column]
                .astype('string')
                .str.strip()
            )

        else:

            if column.endswith('_id'):
                continue
            else:
                df[column] = df[column].fillna(0)

    dict_of_dfs[name] = df

print("Success")

Success

In [93]:
print("ТАБЛИЦА КЛИЕНТОВ")
display(df_customers_clean.head(10))

ТАБЛИЦА КЛИЕНТОВ

,customer_id,full_name,email,phone,city,created_at
0,1,Мишин Емельян Валерьевич,mechislav_37@hotmail.com,UNKNOWN,п. Печора,2024-05-31
1,2,Егоров Тихон Федосеевич,serafim_1986@gmail.com,UNKNOWN,п. Мостовской,2024-07-21
2,3,Зыков Вацлав Алексеевич,fharitonova@gmail.com,9749621470,ст. Луга,2024-06-15
3,4,Савельева Юлия Кузьминична,odintsovgerman@ignatev.biz,NaN,п. Воскресенск,2025-03-28
4,5,София Тимофеевна Михеева,selivan_1979@ao.ru,9206468299,г. Уренгой,2026-01-17
5,6,Варвара Степановна Шилова,aksenovkazimir@rao.biz,9298471886,п. Карпинск,2025-06-15
6,7,Гедеон Феофанович Андреев,belovemmanuil@hotmail.com,NaN,п. Руза,2023-06-08
7,8,Орехова Ангелина Дмитриевна,nonna_92@hotmail.com,+79993631208,клх Красная Поляна,2025-03-05
8,9,София Константиновна Полякова,lavrnekrasov@yahoo.com,NaN,с. Петушки,2024-12-16
9,10,Евдокия Аркадьевна Ларионова,elise1970@gmail.com,9282116655,г. Бийск,2025-09-21

Задание 2. Учту возможные некорретные даты, нечисловые выражения в полях с числами

In [94]:
# некорректные даты
dq_errors = []
date_columns = ['created_at', 'payment_timestamp', 'order_timestamp', 'event_timestamp']
numeric_columns = ['amount', 'price', 'quantity', 'sum']

for table_name, df in dict_of_dfs.items():
    for col in df.columns:
        if col in date_columns:
            # Пробуем конвертировать в дату. Ошибки (2025-99-99) превратятся в NaT
            converted_date = pd.to_datetime(df[col], errors='coerce')
            bad_rows = df[converted_date.isna() & df[col].notna()]

            for idx, row in bad_rows.iterrows():
                dq_errors.append({
                    'table_name': table_name,
                    'column_name': col,
                    'error_type': 'Invalid date format',
                    'bad_value': str(row[col])
                })
            
            # Оставляем в таблице только валидные даты (без NaT)
            df[col] = converted_date
            dict_of_dfs[table_name] = df[df[col].notna()].copy()

# ищем 'error_amount'
for table_name, df in dict_of_dfs.items():
    for col in df.columns:
        if any(x in col.lower() for x in numeric_columns) and df[col].dtype == 'object':
            converted_numeric = pd.to_numeric(df[col], errors='coerce')
            bad_rows = df[converted_numeric.isna() & df[col].notna() & (df[col] != 'Unknown')]
            
            for idx, row in bad_rows.iterrows():
                dq_errors.append({
                    'table_name': table_name,
                    'column_name': col,
                    'error_type': 'Non-numeric value in financial column',
                    'bad_value': str(row[col])
                })
            
            # Оставляем только валидные числа
            df[col] = converted_numeric
            dict_of_dfs[table_name] = df[df[col].notna()].copy()

df_dq_log = pd.DataFrame(dq_errors)
df_dq_log.to_csv('../data/data_errors.csv', index=False)

print(f"-> Обнаружено критических ошибок: {len(df_dq_log)} шт.")

-> Обнаружено критических ошибок: 120 шт.

/var/folders/gq/w6zd94k524d3bqm_6rn2hrp80000gn/T/ipykernel_5738/4245583836.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted_date = pd.to_datetime(df[col], errors='coerce')